
            Element famElm = this.SelectObject(iDoc, doc);

            //conver to family instance 
            Autodesk.Revit.DB.Architecture.Railing instance = famElm as Autodesk.Revit.DB.Architecture.Railing;




            if (famElm != null)
            {
                //get instance geometery
                Options opt = new Options();
                opt.DetailLevel = ViewDetailLevel.Fine;

                GeometryElement geomElm = famElm.get_Geometry(opt);

                var enumu = geomElm.GetEnumerator();
                enumu.MoveNext();
                var ss = enumu.Current;
                //geomElm.GetEnumerator().cu

                var geomObjs = ss as GeometryInstance;

                var geoms = geomObjs.GetInstanceGeometry();
                var allSolids = geoms.Select(g => g as Solid).ToList();
                Solid unionSolid = allSolids.MakeUnion();

                if (unionSolid == null)
                    return Result.Failed;

                XYZ lPt = unionSolid.ComputeCentroid();
                double newX = UnitUtils.ConvertToInternalUnits(lPt.X, UnitTypeId.Millimeters);
                double newY = UnitUtils.ConvertToInternalUnits(lPt.Y, UnitTypeId.Millimeters);
                double newZ = UnitUtils.ConvertToInternalUnits(lPt.Z, UnitTypeId.Millimeters);

                lPt = new XYZ(newX, newY, newZ);

                FamilyInstance fI = FamilyCreation.CreateFamilyByGeometry(doc, lPt, unionSolid, "Test_Railing");
            }